### ISSUE TITLE
Where did you guys find that graphql api?

### ISSUE THREAD

**Issue by zwhitchcox** [aylei/leetcode-rust#12]
I've been looking online, and I can't find any documentation for it. Nice solutions btw.

**Comment by aylei** [comment]
Actually, I find these APIs by reading the code of https://github.com/skygragon/leetcode-cli

**Comment by zwhitchcox** [comment]
Nice! Thank you!

**Comment by Nitigya272001** [comment]
Hey, can anybody please tell me all the endpoints of graphql leetcode api?

**Comment by alexhuang091** [comment]
> Hey, can anybody please tell me all the endpoints of graphql leetcode api?

from https://github.com/shuzijun/leetcode-editor/blob/master/src/main/java/com/shuzijun/leetcode/plugin/utils/URLUtils.java should be `https://leetcode.com/graphql`

**Comment by TieWay59** [comment]
Hi, I learned it today. It's not safe for a company to expose its graphql schema in production, so Leetcode disabled its introspection feature which will let everybody know all the schema. see https://www.apollographql.com/blog/graphql/security/why-you-should-disable-graphql-introspection-in-production/

But there is a workaround. You can open the leetcode website and check the browser network request search for graphql, there would be many graphql requests and you can try to find a needed pattern by reading the payload & response.

Here is an example of `questionOfToday` from https://leetcode.cn/problemset/all/ you'll find similar results in leetcode.com though.

![image](https://user-images.githubusercontent.com/40034603/212425131-c248f366-1340-40e2-ab1c-99da3e59bbf7.png)

@Nitigya272001 I hope this could help you, and I know it's still so tricky because you need to guess some requests might happen on one specific page and read a lot of the web requests.

**Comment by DavidTeju** [comment]
> Hi, I learned it today. It's not safe for a company to expose its graphql schema in production, so Leetcode disabled its introspection feature which will let everybody know all the schema. see https://www.apollographql.com/blog/graphql/security/why-you-should-disable-graphql-introspection-in-production/
> 
> But there is a workaround. You can open the leetcode website and check the browser network request search for graphql, there would be many graphql requests and you can try to find a needed pattern by reading the payload & response.
> 
> Here is an example of `questionOfToday` from https://leetcode.cn/problemset/all/ you'll find similar results in leetcode.com though.
> 
> ![image](https://user-images.githubusercontent.com/40034603/212425131-c248f366-1340-40e2-ab1c-99da3e59bbf7.png)
> 
> @Nitigya272001 I hope this could help you, and I know it's still so tricky because you need to guess some requests might happen on one specific page and read a lot of the web requests.

@TieWay59 Your solution came very in handy for me! Thank you very much!!

**Comment by akarsh1995** [comment]
I've populated a list of all leetcode's GraphQL queries and its postman collection @ [https://github.com/akarsh1995/leetcode-graphql-queries](https://github.com/akarsh1995/leetcode-graphql-queries)
